version: '3'
services:
  logstash:
    image: nbs-logstash
    container_name: logstash
    ports:
      - "8080:8080"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline/json-http.conf:/usr/share/logstash/pipeline/json-http.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./ls_data:/usr/share/logstash/data/
      - ./logs:/var/log/logstash/

    networks:
      - nbs

networks:
  nbs:
    driver: bridge
